import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lista de clientes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="flex justify-center p-2 border shadow-xs">
          <Image
            src="icon.svg"
            alt="Logo da empresa"
            width={26}
            height={26}
            className="mr-2 self-center"
          />
          <h1 className="text-2xl">Clientes</h1>
        </header>

        <main className="flex-grow">
          {children}
        </main>

        <footer className="w-full flex justify-center p-1 border shadow-xs bg-white">
          <h1>&copy; 2025</h1>
        </footer>
      </body>
    </html>

  );
}
